med_ai_site/activities/urls.py
from django.urls import path

from .views import activities

app_name = 'activities'

urlpatterns = [
    path('', activities, name='activities'),
]

med_ai_site/activities/models.py
import datetime

from django.db import models

"""
class Activities(models.Model):
    head = models.TextField(max_length=128, verbose_name='Etkinlik Adı')
    text = models.TextField(max_length=4096, verbose_name='Duyuru Metni')
    banner = ImageField(verbose_name='Afiş')
    doing_date = DateTimeField()
    #coordinator = ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"<{self.doing_date}>{self.head}"

    def is_public(self):
        now = datetime.now()
        return self.doing_date - datetime.timedelta(days=15) <= now <= self.doing_date"""

# Create your models here.

med_ai_site/activities/views.py
from django.shortcuts import render

def activities(request):
    return render(request, 'activities/activities.html')

# Create your views here.

med_ai_site/activities/templates/activities/activities.html
<!DOCTYPE html>
<html lang="tr">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Meram Medicine Faculty Community of Medical Artificial Intelligence</title>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/w3.css' %}">
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  {% load static %}

  <link rel="icon" href="{% static 'logo/med_ai_logo.png' %}" type="PNG">

  <style>
    a:link {
      text-decoration: none;
    }

  </style>
</head>



<body class="w3-teal">


<!-- #############################################################################
#                                   HEADER                                       #
############################################################################## -->

  <header class="w3-teal">
    <div class="w3-row">
      <a href="{% url 'home:home' %}">
        {% load static %}
        
        <img class="w3-col l3" src="{% static 'logo/med_ai_logo.png' %}" alt="png" style="width: 10%; margin-left: 15px;">
      </a>

      <h2 class="w3-col l6 w3-text-white w3-margin-left">Necmettin Erbakan University<br>Medicine Faculty<br>Community of Medical Artificial Intelligence</h2>
      
      <a href="https://www.erbakan.edu.tr/meramtip" target="_blank">
        {% load static %}

        <img class="w3-col l3 w3-margin-top w3-display-topright" src="{% static 'logo/neu_logo.png' %}" alt="png" style="width: 10%;">
      </a>
    </div>
    <div class="w3-center w3-white">
      <div class="w3-bar w3-row w3-white w3-text-teal" style="margin-top: 3px;">
        <a href="{% url 'whoarewe:whoarewe' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Biz Kimiz?</h4></a>
        <a href="{% url 'activities:activities' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Etkinlikler</h4></a>
        <a href="{% url 'workgroups:workgroups' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Çalışma Kollarımız</h4></a>
        <a href="{% url 'projects:projects' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Projelerimiz</h4></a>
        <a href="{% url 'anouncements:anouncements' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Duyurular</h4></a>
        <!--<a href="#"><i class="fa fa-user-md w3-bar-item fa-stack-2x"></i></a>-->
      </div>
    </div>
  </header>



<!-- #############################################################################
#                                   BODY                                         #
############################################################################## -->

  <style>
    .mySlides {display:none;}
  </style>

  <div class="w3-row-padding w3-panel w3-round-large w3-margin w3-center" style="background-color: #D5EEBB;">
    <div class="w3-center" style="margin-top: 64px; margin-bottom: 48px; letter-spacing: 10px; color: teal; font-size: 32px; font-family: 'Times New Roman', Times, serif;">
        ETKİNLİKLER
    </div>
    <div class="w3-content w3-display-container w3-margin-top w3-margin-bottom" style="border: 1px solid black;">
      <div class="w3-round-xlarge">
        <div class="mySlides w3-border w3-round-xlarge w3-animate-opacity">
            <a href="#"><img src="img/resim_1.png" alt="png" style="width: 100%;">
            <div class="w3-display-bottom w3-large w3-container w3-padding-16 w3-blue-grey" style="border-bottom-right-radius: 16px; border-bottom-left-radius: 16px;">
              resim_1
            </div></a>
        </div>
        <div class="mySlides w3-border w3-round-xlarge w3-animate-opacity">
            <a href="#"><img src="img/resim_2.png" alt="png" style="width: 100%;">
            <div class="w3-display-bottom w3-large w3-container w3-padding-16 w3-blue-grey" style="border-bottom-right-radius: 16px; border-bottom-left-radius: 16px;">
              resim_2
            </div></a>
        </div>
        <div class="mySlides w3-border w3-round-xlarge w3-animate-opacity">
            <a href="#"><img src="img/resim_3.png" alt="png" style="width: 100%;">
            <div class="w3-display-bottom w3-large w3-container w3-padding-16 w3-blue-grey" style="border-bottom-right-radius: 16px; border-bottom-left-radius: 16px;">
              resim_3
            </div></a>
        </div>
        <div class="mySlides w3-border w3-round-xlarge w3-animate-opacity">
            <a href="#"><img src="img/resim_4.png" alt="png" style="width: 100%;">
            <div class="w3-display-bottom w3-large w3-container w3-padding-16 w3-blue-grey" style="border-bottom-right-radius: 16px; border-bottom-left-radius: 16px;">
              resim_4
            </div></a>
        </div>
        <div class="mySlides w3-border w3-round-xlarge w3-animate-opacity">
            <a href="#"><img src="img/resim_5.png" alt="png" style="width: 100%;">
            <div class="w3-display-bottom w3-large w3-container w3-padding-16 w3-blue-grey" style="border-bottom-right-radius: 16px; border-bottom-left-radius: 16px;">
              resim_5
            </div></a>
        </div>
        <div class="mySlides w3-border w3-round-xlarge w3-animate-opacity">
            <a href="#"><img src="img/resim_6.gif" alt="png" style="width: 100%; border-top-right-radius: 16px; border-top-left-radius: 16px;">
            <div class="w3-display-bottom w3-large w3-container w3-padding-16 w3-blue-grey" style="border-bottom-right-radius: 16px; border-bottom-left-radius: 16px;">
              resim_6
            </div></a>
        </div>
        <div class="mySlides w3-border w3-round-xlarge w3-animate-opacity">
            <a href="#"><img src="img/cs.jpg" alt="jpg" style="width: 100%; border-top-right-radius: 16px; border-top-left-radius: 16px;">
            <div class="w3-display-bottom w3-large w3-container w3-padding-16 w3-blue-grey" style="border-bottom-right-radius: 16px; border-bottom-left-radius: 16px;">
              cs
            </div></a>
        </div>
        <!--<img class="mySlides w3-border w3-round-xlarge w3-animate-opacity" src="img/resim_1.png" alt="png" style="width: 100%;">
        <img class="mySlides w3-border w3-round-xlarge w3-animate-opacity" src="img/resim_2.png" alt="png" style="width: 100%;">
        <img class="mySlides w3-border w3-round-xlarge w3-animate-opacity" src="img/resim_3.png" alt="png" style="width: 100%;">
        <img class="mySlides w3-border w3-round-xlarge w3-animate-opacity" src="img/resim_4.png" alt="png" style="width: 100%;">
        <img class="mySlides w3-border w3-round-xlarge w3-animate-opacity" src="img/resim_5.png" alt="png" style="width: 100%;">
        <img class="mySlides w3-border w3-round-xlarge w3-animate-opacity" src="img/resim_6.gif" alt="gif" style="width: 100%;">
        <img class="mySlides w3-border w3-round-xlarge w3-animate-opacity" src="img/cs.jpg" alt="jpg" style="width: 100%;">-->
    
        <button class="w3-margin-left w3-button w3-blue-grey w3-display-left w3-round-xxlarge" onclick="plusDivs(-1)">&#10094;</button>
        <button class="w3-margin-right w3-button w3-blue-grey w3-display-right w3-round-xxlarge" onclick="plusDivs(1)">&#10095;</button>


        <!-- BUTTON SCRİPT -->
        <script>
          var slideIndex = 1;
          showDivs(slideIndex);
          
          function plusDivs(n) {
            showDivs(slideIndex += n);
          }
          
          function showDivs(n) {
            var i;
            var x = document.getElementsByClassName("mySlides");
            if (n > x.length) {slideIndex = 1}
            if (n < 1) {slideIndex = x.length}
            for (i = 0; i < x.length; i++) {
              x[i].style.display = "none";  
            }
            x[slideIndex-1].style.display = "block";  
          }
        </script>
  
        <!-- OTO GEÇİŞ SCRİPT -->
        <script>
          var slideIndex = 0;
          carousel();
  
          function carousel() {
            var i;
            var x = document.getElementsByClassName("mySlides");
            for (i = 0; i < x.length; i++) {
              x[i].style.display = "none";
            }
            slideIndex++;
            if (slideIndex > x.length) {slideIndex = 1}
            x[slideIndex-1].style.display = "block";
            setTimeout(carousel, 5000); // Change image every 5 seconds
          }
        </script>
      </div>
    </div>
  </div>


<!-- #############################################################################
#                                   FOOTER                                       #
############################################################################## -->

  <footer class="w3-container w3-row" style="background-color: #464660;">
    <div class="w3-container w3-half w3-row w3-margin-top w3-center">
      <a class="w3-col l1" href="https://www.instagram.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
      </span></a>
      <a class="w3-col l1" href="https://www.twitter.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-twitter-square fa-stack-1x fa-inverse"></i>
      </span></a>
      <a class="w3-col l1" href="https://www.github.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
      </span></a>
      <a class="w3-col l1" href="https://www.youtube.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-youtube-play fa-stack-1x fa-inverse"></i>
      </span></a>
    </div>
    <div class="w3-container w3-center w3-half">
      <div class="w3-container w3-margin-top">Zehra Avan • <a href = "mailto: zehraa@example.com">zehraa@example.com</a></div>
      <div class="w3-container w3-margin-bottom">Nazire Nur Onat • <a href = "mailto: nazire@example.com">nazire@example.com</a></div>
    </div>
  </footer>
  <div class="w3-container w3-center w3-padding">
    © Copyright 2021 Med AI Developer Team
  </div>
  
</body>
</html>