med_ai_site/anouncements/urls.py
from django.urls import path

from .views import anouncements

app_name = 'anouncements'

urlpatterns = [
    path('', anouncements, name='anouncements'),
]

med_ai_site/anouncements/models.py
from django.db import models
from django.db.models.fields.files import ImageField
from django.db.models.fields.related import ForeignKey

"""
class Anouncements(models.Model):
    head = models.TextField(max_length=128)
    text = models.TextField(max_length=4096)
    publication_date = models.DateTimeField()

    def __str__(self) -> str:
        return f"<{self.publication_date}> {self.head}"

class AnonuncemntPhotos(models.Model):
    image = ImageField(verbose_name='Resim')
    anouncement = ForeignKey(Anouncements, on_delete=models.CASCADE)"""

# Create your models here.

med_ai_site/anouncements/views.py
from django.shortcuts import render

def anouncements(request):
    return render(request, 'anouncements/anouncements.html')

# Create your views here.

med_ai_site/anouncements/templates/anouncements/announcements.html
<!DOCTYPE html>
<html lang="tr">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Meram Medicine Faculty Community of Medical Artificial Intelligence</title>
  <link rel="stylesheet" href="w3.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="icon" href="img/med_aı_logo.PNG" type="PNG">

  <style>
    a:link {
      text-decoration: none;
    }

  </style>
</head>



<body class="w3-teal">


<!-- #############################################################################
#                                   HEADER                                       #
############################################################################## -->

  <header class="w3-teal">
    <div class="w3-row">
      <a href="home.html"><img class="w3-col l3" src="img/med_aı_logo.PNG" alt="png" style="width: 10%; margin-left: 15px;"></a>
      <h2 class="w3-col l6 w3-text-white w3-margin-left">Necmettin Erbakan University<br>Medicine Faculty<br>Community of Medical Artificial Intelligence</h2>
      <a href="https://www.erbakan.edu.tr/meramtip" target="_blank"><img class="w3-col l3 w3-margin-top w3-display-topright" src="img/neu_logo.png" alt="png" style="width: 10%;"></a>
    </div>
    <div class="w3-center w3-white">
      <div class="w3-bar w3-row w3-white w3-text-teal" style="margin-top: 3px;">
        <a href="whoarewe.html"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Biz Kimiz?</h4></a>
        <a href="events.html"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Etkinlikler</h4></a>
        <a href="workgroup.html"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Çalışma Kollarımız</h4></a>
        <a href="projects.html"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Projelerimiz</h4></a>
        <a href="announcements.html"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Duyurular</h4></a>
        <a href="#"><i class="fa fa-user-md w3-bar-item fa-stack-2x" style="margin-top: 4px; margin-left: 95%;"></i></a>
      </div>
    </div>
  </header>


<!-- #############################################################################
#                                   BODY                                         #
############################################################################## -->

  <div class="w3-row-padding w3-panel w3-round-large w3-margin w3-center" style="background-color: #D5EEBB;">
    <div class="w3-center w3-margin-bottom" style="margin-top: 64px; letter-spacing: 10px; color: teal; font-size: 32px; font-family: 'Times New Roman', Times, serif;">
        DUYURULAR
    </div>
    <div class="w3-container w3-margin-top w3-margin-bottom" style="border: 1px solid black; margin-left: 144px; margin-right: 144px;">
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
    </div>
  </div>


<!-- #############################################################################
#                                   FOOTER                                       #
############################################################################## -->

  <footer class="w3-container w3-row" style="background-color: #464660;">
    <div class="w3-container w3-half w3-row w3-margin-top w3-center">
      <a class="w3-col l1" href="https://www.instagram.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
      </span></a>
      <a class="w3-col l1" href="https://www.twitter.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-twitter-square fa-stack-1x fa-inverse"></i>
      </span></a>
      <a class="w3-col l1" href="https://www.github.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
      </span></a>
      <a class="w3-col l1" href="https://www.youtube.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-youtube-play fa-stack-1x fa-inverse"></i>
      </span></a>
    </div>
    <div class="w3-container w3-center w3-half">
      <div class="w3-container w3-margin-top">Zehra Avan • <a href = "mailto: zehraa@example.com">zehraa@example.com</a></div>
      <div class="w3-container w3-margin-bottom">Nazire Nur Onat • <a href = "mailto: nazire@example.com">nazire@example.com</a></div>
    </div>
  </footer>
  <div class="w3-container w3-center w3-padding">
    © Copyright 2021 Med AI Developer Team
  </div>
  
</body>
</html>

med_ai_site/anouncements/templates/anouncements/anouncements.html
<!DOCTYPE html>
<html lang="tr">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Meram Medicine Faculty Community of Medical Artificial Intelligence</title>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/w3.css' %}">
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  {% load static %}

  <link rel="icon" href="{% static 'logo/med_ai_logo.png' %}" type="PNG">

  <style>
    a:link {
      text-decoration: none;
    }

  </style>
</head>



<body class="w3-teal">


<!-- #############################################################################
#                                   HEADER                                       #
############################################################################## -->

  <header class="w3-teal">
    <div class="w3-row">
      <a href="{% url 'home:home' %}">
        {% load static %}
        
        <img class="w3-col l3" src="{% static 'logo/med_ai_logo.png' %}" alt="png" style="width: 10%; margin-left: 15px;">
      </a>

      <h2 class="w3-col l6 w3-text-white w3-margin-left">Necmettin Erbakan University<br>Medicine Faculty<br>Community of Medical Artificial Intelligence</h2>
      
      <a href="https://www.erbakan.edu.tr/meramtip" target="_blank">
        {% load static %}

        <img class="w3-col l3 w3-margin-top w3-display-topright" src="{% static 'logo/neu_logo.png' %}" alt="png" style="width: 10%;">
      </a>
    </div>
    <div class="w3-center w3-white">
      <div class="w3-bar w3-row w3-white w3-text-teal" style="margin-top: 3px;">
        <a href="{% url 'whoarewe:whoarewe' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Biz Kimiz?</h4></a>
        <a href="{% url 'activities:activities' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Etkinlikler</h4></a>
        <a href="{% url 'workgroups:workgroups' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Çalışma Kollarımız</h4></a>
        <a href="{% url 'projects:projects' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Projelerimiz</h4></a>
        <a href="{% url 'anouncements:anouncements' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Duyurular</h4></a>
        <!--<a href="#"><i class="fa fa-user-md w3-bar-item fa-stack-2x"></i></a>-->
      </div>
    </div>
  </header>


<!-- #############################################################################
#                                   BODY                                         #
############################################################################## -->

  <div class="w3-row-padding w3-panel w3-round-large w3-margin w3-center" style="background-color: #D5EEBB;">
    <div class="w3-center w3-margin-bottom" style="margin-top: 64px; letter-spacing: 10px; color: teal; font-size: 32px; font-family: 'Times New Roman', Times, serif;">
        DUYURULAR
    </div>
    <div class="w3-container w3-margin-top w3-margin-bottom" style="border: 1px solid black; margin-left: 144px; margin-right: 144px;">
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
        <div class="w3-col l2 w3-center w3-row-padding">
          <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
            <h1 class="w3-text-teal" style="font-size: 64px; padding-top: 36px; line-height: 36px;">13</h1>
            <h3 class="w3-text-teal" style="font-size: 32px;">Eylül</h3>
            <div class="w3-row-padding w3-padding-16">MTF yeni döneme başladı.</div>
          </div></a>
        </div>
    </div>
  </div>


<!-- #############################################################################
#                                   FOOTER                                       #
############################################################################## -->

  <footer class="w3-container w3-row" style="background-color: #464660;">
    <div class="w3-container w3-half w3-row w3-margin-top w3-center">
      <a class="w3-col l1" href="https://www.instagram.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
      </span></a>
      <a class="w3-col l1" href="https://www.twitter.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-twitter-square fa-stack-1x fa-inverse"></i>
      </span></a>
      <a class="w3-col l1" href="https://www.github.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
      </span></a>
      <a class="w3-col l1" href="https://www.youtube.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-youtube-play fa-stack-1x fa-inverse"></i>
      </span></a>
    </div>
    <div class="w3-container w3-center w3-half">
      <div class="w3-container w3-margin-top">Zehra Avan • <a href = "mailto: zehraa@example.com">zehraa@example.com</a></div>
      <div class="w3-container w3-margin-bottom">Nazire Nur Onat • <a href = "mailto: nazire@example.com">nazire@example.com</a></div>
    </div>
  </footer>
  <div class="w3-container w3-center w3-padding">
    © Copyright 2021 Med AI Developer Team
  </div>
  
</body>
</html>