med_ai_site/workgroups/urls.py
from django.urls import path

from .views import workgroups, workgroup

app_name = 'workgroups'

urlpatterns = [
    path('', workgroups, name='workgroups'),
    path('<int:team_id>workgroup/', workgroup, name='workgroup'),
]

med_ai_site/workgroups/models.py
from django.db import models
from home.models import User


class Team(models.Model):
    team_name = models.TextField(max_length=64)
    description = models.TextField(max_length=4096)
    stylist_name = models.TextField(max_length=64)
    team_leader = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.stylist_name}: {self.team_name}"

# Create your models here.

med_ai_site/workgroups/views.py
from django.shortcuts import render
from .models import Team

def workgroups(request):
    teams = Team.objects.all()
    print(teams)
    print(teams[0].team_name)
    context = {
        'teams': teams
    }
    return render(request, 'workgroups/workgroups.html', context)

def workgroup(request, team_id):
    team = Team.objects.get(pk=team_id)
    context = {
        'team': team,
        'leader': team.team_leader
    }
    return render(request, 'workgroups/workgroup.html', context)

# Create your views here.

med_ai_site/workgroups/templates/workgroups/workgroup.html
<!DOCTYPE html>
<html>
  <head>
    <title>Medical Artificial Intelligence</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'home/css/w3.css' %}"> <!-- w3.css File -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> <!-- Sosyal Medya Logo -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'home/css/med_ai.css' %}">

    <!-- MENU BAR ITEM BUTTON SCRIPT -->
    <script>
      function w3_open() {
        document.getElementById("main").style.marginLeft = "15%";
        document.getElementById("mySidebar").style.width = "15%";
        document.getElementById("mySidebar").style.display = "block";
        document.getElementById("openNav").style.display = 'none';
      }
      function w3_close() {
        document.getElementById("main").style.marginLeft = "0%";
        document.getElementById("mySidebar").style.display = "none";
        document.getElementById("openNav").style.display = "inline-block";
      }
    </script>
      

  </head>

  <body class="w3-black">
    
    <!-- Menu Bar Items -->
    <div class="w3-sidebar w3-bar-block w3-card w3-animate-left w3-black w3-border-right" style="display:none;" id="mySidebar">
      <button class="w3-bar-item w3-button w3-large" onclick="w3_close()">
        Close &times;
      </button>
      <a href="{% url 'home:home' %}" class="w3-bar-item w3-button">Ana Sayfa</a>
      <a href="{% url 'whoarewe:whoarewe' %}" class="w3-bar-item w3-button">Hakkımızda</a>
      <a href="{% url 'workgroups:workgroups' %}" class="w3-bar-item w3-button">Çalışma Grupları</a>
      <a href="{% url 'activities:activities' %}" class="w3-bar-item w3-button">Etkinlikler</a>
      <a href="{% url 'projects:projects' %}" class="w3-bar-item w3-button">Projeler</a>
    </div>
    <!--##############################################################-->
    <!-- HEADER -->
    <!--##############################################################-->
    <header class="ai-back-color" id="main">
      <!-- Menu Bar Opening Button -->
      <button id="openNav" class="w3-button w3-black w3-xlarge" onclick="w3_open()">
        &#9776;
      </button>
      <!--#########################################################-->
      <!-- Social Media Links -->
      <!--#########################################################-->
      
      <!-- Instagram -->
      <a class="l1" href="https://www.instagram.com/" target="_blank">
        <span class="fa-stack fa-lg">
          <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
        </span></a>
      <!-- Twitter -->
      <a class="l1" href="https://www.twitter.com/" target="_blank">
        <span class="fa-stack fa-lg">
          <i class="fa fa-twitter-square fa-stack-1x fa-inverse"></i>
        </span></a>
      <!-- GitHub -->
      <a class="l1" href="https://www.github.com/" target="_blank">
        <span class="fa-stack fa-lg">
          <i class="fa fa-github fa-stack-1x fa-inverse"></i>
        </span></a>
      <!-- YouTube -->
      <a class="l1" href="https://www.youtube.com/" target="_blank">
        <span class="fa-stack fa-lg">
        <i class="fa fa-youtube-play fa-stack-1x fa-inverse"></i>
        </span></a>
    </header>
    
    <!--##############################################################-->
    <!-- BODY -->
    <!--##############################################################-->
    <div class="w3-container w3-center w3-animate-bottom w3-margin">
      <div class="w3-container w3-animate-bottom">
        <div class="w3-row">
          <!-- Margin Left -->
          <div class="w3-col l1 w3-panel"></div>
          <!-- Team Card -->
          <div class="w3-panel w3-col l10 w3-margin w3-round-large ai-teams-card">
            <!-- Team Name -->
            <h2 class="ai-about-us-head">
                {{team.team_name}}
            </h2>
            <div>
              {{team.description}}
            </div>
            <!-- Communicate Area -->
            <div>
              <!-- Team Communication -->
              <h3 class="ai-about-us-head">
                  İletişim
              </h3>
              <div>
                <span style="color: orange;">def</span> <span style="color: greenyellow;">User:</span>
                <br><span style="color: turquoise;">&emsp;Name:</span>
                <br>&emsp;&emsp;{{leader.name}}
                <br><span style="color: turquoise;">&emsp;SurName:</span>
                <br>&emsp;&emsp;{{leader.surname}}
                <br><span style="color: turquoise;">&emsp;Email:</span>
                <br>&emsp;&emsp;{{leader.email}}
                <br><span style="color: turquoise;">&emsp;PhoneNumber:</span>
                <br>&emsp;&emsp;{{leader.phone_number}}
              </div>
            </div>
          </div>
          <!-- Margin Right -->
          <div class="w3-col l1 w3-panel"></div>
        </div>
      </div>
    </div>

    <!--##############################################################-->
    <!-- FOOTER -->
    <!--##############################################################-->
    <footer class="w3-container w3-row w3-center w3-margin">
      <!-- TROL -->
      <div>
        :)
      </div>
      <!-- License -->
      <div class="w3-container w3-center w3-padding ai-font-size">
        © Copyright 2021 Med AI Developer Team
      </div>  
    </footer>
  </body>
</html>

med_ai_site/workgroups/templates/workgroups/workgroups.html
<!DOCTYPE html>
<html>
  <head>
    <title>Medical Artificial Intelligence</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'home/css/w3.css' %}"> <!-- w3.css File -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> <!-- Sosyal Medya Logo -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'home/css/med_ai.css' %}">

    <!-- MENU BAR ITEM BUTTON SCRIPT -->
    <script>
      function w3_open() {
        document.getElementById("main").style.marginLeft = "15%";
        document.getElementById("mySidebar").style.width = "15%";
        document.getElementById("mySidebar").style.display = "block";
        document.getElementById("openNav").style.display = 'none';
      }
      function w3_close() {
        document.getElementById("main").style.marginLeft = "0%";
        document.getElementById("mySidebar").style.display = "none";
        document.getElementById("openNav").style.display = "inline-block";
      }
    </script>
      

  </head>

  <body class="w3-black">
    
    <!-- Menu Bar Items -->
    <div class="w3-sidebar w3-bar-block w3-card w3-animate-left w3-black w3-border-right" style="display:none;" id="mySidebar">
      <button class="w3-bar-item w3-button w3-large" onclick="w3_close()">
        Close &times;
      </button>
      <a href="{% url 'home:home' %}" class="w3-bar-item w3-button">Ana Sayfa</a>
      <a href="{% url 'whoarewe:whoarewe' %}" class="w3-bar-item w3-button">Hakkımızda</a>
      <a href="{% url 'workgroups:workgroups' %}" class="w3-bar-item w3-button">Çalışma Grupları</a>
      <a href="{% url 'activities:activities' %}" class="w3-bar-item w3-button">Etkinlikler</a>
      <a href="{% url 'projects:projects' %}" class="w3-bar-item w3-button">Projeler</a>
    </div>
    <!--##############################################################-->
    <!-- HEADER -->
    <!--##############################################################-->
    <header class="ai-back-color" id="main">
      <!-- Menu Bar Opening Button -->
      <button id="openNav" class="w3-button w3-black w3-xlarge" onclick="w3_open()">
        &#9776;
      </button>
      <!--#########################################################-->
      <!-- Social Media Links -->
      <!--#########################################################-->
      
      <!-- Instagram -->
      <a class="l1" href="https://www.instagram.com/" target="_blank">
        <span class="fa-stack fa-lg">
          <i class="fa fa-instagram fa-stack-1x fa-inverse"></i></span></a>
      <!-- Twitter -->
      <a class="l1" href="https://www.twitter.com/" target="_blank">
        <span class="fa-stack fa-lg">
          <i class="fa fa-twitter-square fa-stack-1x fa-inverse"></i>
        </span></a>
      <!-- GitHub -->
      <a class="l1" href="https://www.github.com/" target="_blank">
        <span class="fa-stack fa-lg">
          <i class="fa fa-github fa-stack-1x fa-inverse"></i>
        </span></a>
      <!-- YouTube -->
      <a class="l1" href="https://www.youtube.com/" target="_blank">
        <span class="fa-stack fa-lg">
        <i class="fa fa-youtube-play fa-stack-1x fa-inverse"></i>
        </span></a>
    </header>
    <!--##############################################################-->
    <!-- BODY -->
    <!--##############################################################-->
    <div class="w3-container  w3-animate-bottom w3-margin">
      <div class="w3-container w3-animate-bottom">
        <div class="w3-row">
          <!-- Margin Left -->
          <div class="w3-col l1 w3-panel"></div>
          {% for team in teams %}
          <!-- Team Link -->
          <a href="{% url 'workgroups:workgroup' team.id %}">
          
            <div class="w3-panel w3-col l3 w3-margin w3-round-large ai-teams-card">
              <img class="w3-margin" src="img/eagle.png" alt="">
              <!-- Team Name -->
              <h2 class="w3-margin w3-center ai-about-us-head">
                <span style="color:red;">&lt/</span>{{ team.team_name }}<span style="color:red;">&gt</span>
              </h2>
              <!-- Stilize Team Name -->
              <div style="color: turquoise;"><span style="color: orange;">class</span> {{ team.stylist_name }}(<span style="color: rgb(98,228,86)">Team</span>):</div>
              <!-- Team Description -->
              <div class="w3-margin-left w3-margin-bottom">
                {{team.description}}
              </div>
            </div>
          </a>
              {% endfor %}
          <!-- Margin Right -->
          <div class="w3-col l1 w3-panel"></div>
        </div>
    </div>


<!--##############################################################-->
    <!-- FOOTER -->
    <!--##############################################################-->
    <footer class="w3-container w3-row w3-center w3-margin">
      <!-- TROL -->
      <div>
        :)
      </div>
      <!-- License -->
      <div class="w3-container w3-center w3-padding ai-font-size">
        © Copyright 2021 Med AI Developer Team
      </div>  
    </footer>
  </body>
</html>