med_ai_site/projects/urls.py
from django.urls import path

from .views import projects

app_name = 'projects'

urlpatterns = [
    path('', projects, name='projects'),
]

med_ai_site/projects/models.py
from django.db import models
from home.models import User

"""class Project(models.Model):
    project_name = models.TextField(max_length=128)
    project_description = models.TextField(max_length=4096)
    project_manager = models.ForeignKey(User, on_delete=models.CASCADE)
    project_logo = models.ImageField()
"""



# Create your models here.

med_ai_site/projects/views.py
from django.shortcuts import render

def projects(request):
    return render(request, 'projects/projects.html')

# Create your views here.

med_ai_site/projects/templates/projects/projects.html
<!DOCTYPE html>
<html lang="tr">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Meram Medicine Faculty Community of Medical Artificial Intelligence</title>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/w3.css' %}">
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  {% load static %}

  <link rel="icon" href="{% static 'logo/med_ai_logo.png' %}" type="PNG">

  <style>
    a:link {
      text-decoration: none;
    }

  </style>
</head>



<body class="w3-teal">


<!-- #############################################################################
#                                   HEADER                                       #
############################################################################## -->

  <header class="w3-teal">
    <div class="w3-row">
      <a href="{% url 'home:home' %}">
        {% load static %}
        
        <img class="w3-col l3" src="{% static 'logo/med_ai_logo.png' %}" alt="png" style="width: 10%; margin-left: 15px;">
      </a>

      <h2 class="w3-col l6 w3-text-white w3-margin-left">Necmettin Erbakan University<br>Medicine Faculty<br>Community of Medical Artificial Intelligence</h2>
      
      <a href="https://www.erbakan.edu.tr/meramtip" target="_blank">
        {% load static %}

        <img class="w3-col l3 w3-margin-top w3-display-topright" src="{% static 'logo/neu_logo.png' %}" alt="png" style="width: 10%;">
      </a>
    </div>
    <div class="w3-center w3-white">
      <div class="w3-bar w3-row w3-white w3-text-teal" style="margin-top: 3px;">
        <a href="{% url 'whoarewe:whoarewe' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Biz Kimiz?</h4></a>
        <a href="{% url 'activities:activities' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Etkinlikler</h4></a>
        <a href="{% url 'workgroups:workgroups' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Çalışma Kollarımız</h4></a>
        <a href="{% url 'projects:projects' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Projelerimiz</h4></a>
        <a href="{% url 'anouncements:anouncements' %}"><h4 class="w3-bar-item w3-hover-teal w3-text-hover-teal w3-round-xxlarge w3-margin-left w3-margin-right" style="margin-top: 2px; margin-bottom: 2px;">Duyurular</h4></a>
        <!--<a href="#"><i class="fa fa-user-md w3-bar-item fa-stack-2x"></i></a>-->
      </div>
    </div>
  </header>


<!-- #############################################################################
#                                   BODY                                         #
############################################################################## -->

  <div class="w3-row-padding w3-panel w3-round-large w3-margin w3-center" style="background-color: #D5EEBB;">
    <div class="w3-center" style="margin-top: 64px; margin-bottom: 48px; letter-spacing: 10px; color: teal; font-size: 32px; font-family: 'Times New Roman', Times, serif;">
        PROJELER
    </div>
    <div class="w3-container w3-col l6 w3-center w3-margin-top w3-margin-bottom" style="border: 1px solid red;">
      <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
        <img src="img/resim_6.gif" alt="gif" style="width: 90%;" class="w3-padding-16 w3-round-xxlarge">
        <h2 class="w3-text-teal" style="line-height: 32px;">Kulüp Olarak İlk Projemizi Tamamladık</h2>
        <div class="w3-row-padding w3-padding-16">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam provident nobis asperiores cupiditate earum maxime incidunt voluptatem error autem, fuga, dolore ipsa ratione, voluptatum ipsam. Eum et quos odio aut!</div>
      </div></a>
    </div>
    <div class="w3-container w3-col l6 w3-center w3-margin-top w3-margin-bottom" style="border: 1px solid purple;">
      <a href="#"><div class="w3-card w3-center w3-white w3-round-large">
        <img src="img/resim_6.gif" alt="gif" style="width: 90%;" class="w3-padding-16 w3-round-xxlarge">
        <h2 class="w3-text-teal" style="line-height: 32px;">Kulüp Olarak İlk Projemizi Tamamladık</h2>
        <div class="w3-row-padding w3-padding-16">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam provident nobis asperiores cupiditate earum maxime incidunt voluptatem error autem, fuga, dolore ipsa ratione, voluptatum ipsam. Eum et quos odio aut!</div>
      </div></a>
    </div>
  </div>


<!-- #############################################################################
#                                   FOOTER                                       #
############################################################################## -->

  <footer class="w3-container w3-row" style="background-color: #464660;">
    <div class="w3-container w3-half w3-row w3-margin-top w3-center">
      <a class="w3-col l1" href="https://www.instagram.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
      </span></a>
      <a class="w3-col l1" href="https://www.twitter.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-twitter-square fa-stack-1x fa-inverse"></i>
      </span></a>
      <a class="w3-col l1" href="https://www.github.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
      </span></a>
      <a class="w3-col l1" href="https://www.youtube.com/" target="_blank"><span class="fa-stack fa-lg">
        <i class="fa fa-youtube-play fa-stack-1x fa-inverse"></i>
      </span></a>
    </div>
    <div class="w3-container w3-center w3-half">
      <div class="w3-container w3-margin-top">Zehra Avan • <a href = "mailto: zehraa@example.com">zehraa@example.com</a></div>
      <div class="w3-container w3-margin-bottom">Nazire Nur Onat • <a href = "mailto: nazire@example.com">nazire@example.com</a></div>
    </div>
  </footer>
  <div class="w3-container w3-center w3-padding">
    © Copyright 2021 Med AI Developer Team
  </div>
  
</body>
</html>